#!/bin/bash
# Derek Moore <derek.moore@gmail.com>

usage() {
    echo "Usage: $0 -c CERT -r REASON"
    echo "Revokes a certificate issued by this CA"
    echo
    echo "Options:"
    echo "    -c CERT  Path the the certificate file to be revoked"
    echo "    -r REASON"
    echo "        Reason for revocation: "
    echo "            1. unspecified"
    echo "            2. keyCompromise"
    echo "            3. CACompromise"
    echo "            4. affiliationChanged"
    echo "            5. superseded"
    echo "            6. cessationOfOperation"
    echo "            7. certificateHold"
    echo
    exit 2
}

CERT=

while getopts "c:r:" FLAG; do
    case "${FLAG}" in
        c) CERT=${OPTARG} ;;
        r) case ${OPTARG} in
            1) REASON="unspecified" ;;
            2) REASON="keyCompromise" ;;
            3) REASON="CACompromise" ;;
            4) REASON="affiliationChanged" ;;
            5) REASON="superseded" ;;
            6) REASON="cessationOfOperation" ;;
            7) REASON="certificateHold" ;;
            *) usage ;;
            esac
            ;;
        *) usage ;;
    esac
done

if [ "${CERT}" == "" ]; then
    usage
fi
if [ "${REASON}" == "" ]; then
    usage
fi

BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${BIN_DIR}/functions
source ${BIN_DIR}/defaults.conf

echo
echo "Revoking certificate '${CERT}'"
echo

if [ ! -f "${CERT}" ]; then
    echo "Could not read certificate '${CERT}', exiting."
    exit 1
fi

# Fully-qualify path to cert
CERT=$( fullpath ${CERT} )

pushd ${BIN_DIR}/.. > /dev/null

# Revoke the certificate
openssl ca \
           -config conf/ca.conf \
           -revoke ${CERT} \
           -crl_reason ${REASON}

# Regenerate the CRL
openssl ca -gencrl \
           -config conf/ca.conf \
           -out crl/ca.crl

popd > /dev/null

echo
echo "Server certificate revoked."
echo

